language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r first-springboot *
  - mkdir -p deploy
  - mv first-springboot.zip deploy/first-springboot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: njhyuk-first-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#  - provider: codedeploy
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
#    bucket: njhyuk-first-springboot
#    key: first-springboot.zip
#    bundle_type: zip
#    application: first-springboot
#    deployment_group: first-springboot-group
#    region: ap-northeast-2
#    wait-until-deployed: true

  notifications:
    email:
      recipients:
        - njh2239@gmail.com